// codegen.cpp - Phase 4: checked AST -> Python
#include "codegen.h"
using namespace std;

string CodeGenerator::generate(NodePtr program) {
    emit("# Generated by Bangla Compiler");
    for (NodePtr statement : program->children) genStatement(statement);

    string result;
    for (const string& line : lines) result += line + "\n";
    return result;
}

void CodeGenerator::emit(const string& line) {
    lines.push_back(string(indent * 4, ' ') + line);
}

void CodeGenerator::genBlock(NodePtr block) {
    indent++;
    size_t before = lines.size();
    for (NodePtr statement : block->children) genStatement(statement);
    if (lines.size() == before) emit("pass");     // empty block
    indent--;
}

void CodeGenerator::genStatement(NodePtr n) {
    switch (n->kind) {
        case N_DECLARE: {
            string value = (n->type == TYPE_INT) ? "0" : "0.0";   // default value
            if (!n->children.empty()) value = convert(n->type, n->children[0]);
            emit(n->text + " = " + value);
            break;
        }
        case N_ASSIGN:
            emit(n->text + " = " + convert(n->type, n->children[0]));
            break;

        case N_IF:
            emit("if " + genExpr(n->children[0]) + ":");
            genBlock(n->children[1]);
            if (n->children.size() > 2) {
                emit("else:");
                genBlock(n->children[2]);
            }
            break;

        case N_WHILE:
            emit("while " + genExpr(n->children[0]) + ":");
            genBlock(n->children[1]);
            break;

        case N_PRINT: {
            string args;
            for (NodePtr item : n->children) {
                if (!args.empty()) args += ", ";
                args += genExpr(item);
            }
            emit("print(" + args + ")");
            break;
        }
        default: break;
    }
}

// purno stored into a doshomik variable -> float(...)
string CodeGenerator::convert(Type target, NodePtr value) {
    string code = genExpr(value);
    if (target == TYPE_FLOAT && value->type == TYPE_INT) return "float(" + code + ")";
    return code;
}

string CodeGenerator::genExpr(NodePtr n) {
    switch (n->kind) {
        case N_INT:
        case N_FLOAT:
        case N_VAR:     return n->text;
        case N_STRING:  return "\"" + escape(n->text) + "\"";
        case N_NEGATE:  return "-" + operand(n->children[0]);
        case N_COMPARE: return genExpr(n->children[0]) + " " + n->text + " "
                             + genExpr(n->children[1]);
        case N_BINARY: {
            NodePtr left = n->children[0];
            NodePtr right = n->children[1];
            string op = n->text;
            // purno / purno stays a whole number -> // in Python
            if (op == "/" && left->type == TYPE_INT && right->type == TYPE_INT) op = "//";
            return operand(left) + " " + op + " " + operand(right);
        }
        default: return "";
    }
}

// put ( ) around a nested calculation so the order stays correct
string CodeGenerator::operand(NodePtr n) {
    string code = genExpr(n);
    if (n->kind == N_BINARY) return "(" + code + ")";
    return code;
}

string CodeGenerator::escape(const string& s) {
    string result;
    for (char c : s) {
        if (c == '\\') result += "\\\\";
        else result += c;
    }
    return result;
}
